# Github action to automatically create a github release on merge to main.
# Skips if a release already exists with the version defined in Cargo.toml.
name: Create Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: manoadamro/rust-release@v1
        with:
            owner: ${{ github.repository_owner }}
            repo: ${{ github.repository }}
            token: ${{ secrets.GITHUB_TOKEN }}
